version = "1.0"

[metadata]
name = "CCX-dep-trace-264"
description = "Firefox SpiderMonkey JS Parsing to Bytecode Chain"
license = "Apache-2.0"

[task]
id = "CCX-dep-trace-264"
repo = "sg-evals/firefox--871325b8"
category = "cross-repo-dep-trace"
language = "cpp"
difficulty = "hard"
time_limit_sec = 900
mcp_suite = "csb_org_crossrepo"
use_case_id = 264
repo_set_id = "mozilla-firefox"
mcp_unique = true
verification_modes = ["artifact"]

[verification]
type = "test"
command = "bash /tests/test.sh"

reward_type = "score"
description = "Firefox SpiderMonkey JS Parsing to Bytecode Chain"

[environment]
build_timeout_sec = 600.0
