version = "1.0"

[metadata]
name = "CCX-dep-trace-271"
description = "OpenJDK G1 GC Garbage Collection Cycle Chain"
license = "Apache-2.0"

[task]
id = "CCX-dep-trace-271"
repo = "sg-evals/jdk--742e735d"
category = "cross-repo-dep-trace"
language = "java,cpp"
difficulty = "hard"
time_limit_sec = 900
mcp_suite = "csb_org_crossrepo"
use_case_id = 271
repo_set_id = "java-platform"
mcp_unique = true
verification_modes = ["artifact"]

[verification]
type = "test"
command = "bash /tests/test.sh"

reward_type = "score"
description = "OpenJDK G1 GC Garbage Collection Cycle Chain"

[environment]
build_timeout_sec = 600.0
