#!/usr/bin/env python3
"""Context retrieval agent with multiple backends for oracle cross-validation.

Generates oracle ground truth files by running a Claude-powered agent with
configurable tool backends:

  local     - grep, ripgrep, find, file reading (no external services)
  deepsearch - Sourcegraph Deep Search (mcp__sourcegraph__deepsearch)
  hybrid    - both local tools AND deep search (default)

Cross-validation compares oracles generated by different backends. If
agreement between local-only and deepsearch-only is high (>80% file F1),
the circularity concern is empirically defused.

Environment variables:
    CLAUDE_CODE_OAUTH_TOKEN     Preferred. OAuth token for subscription billing.
    ANTHROPIC_API_KEY           Fallback. Claude API key.
    SOURCEGRAPH_ACCESS_TOKEN    Required for deepsearch/hybrid backends.
    SOURCEGRAPH_URL             SG instance (default: https://sourcegraph.sourcegraph.com)
    CCB_REPO_CACHE              Repo clone cache dir (default: ~/.cache/ccb_repos)

Usage:
    # Single task with hybrid backend (default)
    python3 scripts/context_retrieval_agent.py \\
        --task-dir benchmarks/ccb_mcp_crossrepo_tracing/ccx-dep-trace-001

    # Local-only backend (for cross-validation against SG oracle)
    python3 scripts/context_retrieval_agent.py \\
        --task-dir benchmarks/ccb_fix/kafka-producer-bufpool-fix-001 \\
        --backend local

    # Cross-validate: run all backends on same tasks, compare agreement
    python3 scripts/context_retrieval_agent.py \\
        --task-dir benchmarks/ccb_mcp_crossrepo_tracing/ccx-dep-trace-001 \\
        --cross-validate

    # Cheaper model for batch runs
    python3 scripts/context_retrieval_agent.py --sdlc-all \\
        --model claude-sonnet-4-6 --max-cost 20.00

    # Dry run
    python3 scripts/context_retrieval_agent.py --task-dir <dir> --dry-run
"""

import argparse
import json
import logging
import os
import re
import shlex
import subprocess
import tempfile
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

try:
    import anthropic
    HAS_ANTHROPIC = True
except ImportError:
    HAS_ANTHROPIC = False

log = logging.getLogger("context_retrieval_agent")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_MODEL = "claude-opus-4-6"  # Strongest model for oracle generation
MAX_TOKENS = 16384
MAX_TOOL_CALLS = 40
TOOL_TIMEOUT_SEC = 30
TASK_TIMEOUT_SEC = 600  # 10 minutes per task (Deep Search calls take 30-60s each)
DEFAULT_CACHE_DIR = Path.home() / ".cache" / "ccb_repos"

BACKENDS = ("local", "deepsearch", "hybrid")

# Cost per 1M tokens (2026-03 pricing)
MODEL_COSTS = {
    "claude-opus-4-6": {"input": 15.0, "output": 75.0},
    "claude-sonnet-4-6": {"input": 3.0, "output": 15.0},
    "claude-haiku-4-5-20251001": {"input": 0.80, "output": 4.0},
}

SDLC_SUITES = [
    "ccb_fix", "ccb_feature", "ccb_debug", "ccb_design",
    "ccb_document", "ccb_refactor", "ccb_secure", "ccb_test",
    "ccb_understand",
]

MCP_UNIQUE_SUITES = [
    "ccb_mcp_crossrepo_tracing", "ccb_mcp_crossrepo", "ccb_mcp_crossorg",
    "ccb_mcp_compliance", "ccb_mcp_domain", "ccb_mcp_incident",
    "ccb_mcp_migration", "ccb_mcp_onboarding", "ccb_mcp_org",
    "ccb_mcp_platform", "ccb_mcp_security",
]

# ---------------------------------------------------------------------------
# Deep Search tool (Sourcegraph)
# ---------------------------------------------------------------------------

DEEPSEARCH_TOOL = {
    "name": "deep_search",
    "description": (
        "Run a Sourcegraph Deep Search query against indexed repositories. "
        "This uses AI-powered semantic code search to find relevant files, "
        "symbols, and code patterns across the codebase. Returns a curated "
        "summary of findings with file paths and code snippets. "
        "Use this for broad exploration and to find things that keyword "
        "grep might miss (e.g., semantic relationships, design patterns)."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": (
                    "Natural language or keyword query describing what to find. "
                    "Be specific about repos, languages, and concepts."
                ),
            },
            "repos": {
                "type": "array",
                "items": {"type": "string"},
                "description": (
                    "Repository names to search (e.g., ['github.com/sg-evals/kafka--0753c489']). "
                    "If empty, searches all indexed repos."
                ),
            },
        },
        "required": ["query"],
    },
}

KEYWORD_SEARCH_TOOL = {
    "name": "sourcegraph_search",
    "description": (
        "Run a Sourcegraph keyword code search. Returns matching code snippets "
        "with file paths and line numbers. Use for exact string/regex matches "
        "across repositories. More precise than deep_search but less semantic."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": (
                    "Sourcegraph search query. Can include filters like "
                    "repo:, file:, lang:. Example: 'repo:^github.com/foo$ MyClass'"
                ),
            },
        },
        "required": ["query"],
    },
}


class SourcegraphClient:
    """Minimal Sourcegraph API client for deep search and keyword search."""

    def __init__(self, url: str = "", token: str = ""):
        self.url = url or os.environ.get(
            "SOURCEGRAPH_URL",
            os.environ.get("SRC_ENDPOINT", "https://sourcegraph.sourcegraph.com"),
        )
        self.token = token or os.environ.get(
            "SOURCEGRAPH_ACCESS_TOKEN",
            os.environ.get("SRC_ACCESS_TOKEN", ""),
        )
        if not self.token:
            log.warning("No Sourcegraph token — deepsearch/hybrid backends unavailable")
        else:
            # Validate token at init
            self._validate_token()

    def _headers(self) -> dict:
        """Standard headers for SG API requests (includes User-Agent to avoid Cloudflare 1010)."""
        return {
            "Authorization": f"token {self.token}",
            "Content-Type": "application/json",
            "User-Agent": "ccb-context-retrieval-agent/1.0",
        }

    def _validate_token(self) -> None:
        """Check that the token is valid by running a simple query."""
        import urllib.request
        import urllib.error

        gql = 'query { currentUser { username } }'
        body = json.dumps({"query": gql}).encode()
        req = urllib.request.Request(
            f"{self.url.rstrip('/')}/.api/graphql",
            data=body,
            headers=self._headers(),
        )
        try:
            with urllib.request.urlopen(req, timeout=10) as resp:
                data = json.loads(resp.read())
                user = data.get("data", {}).get("currentUser", {})
                if user:
                    log.info("SG auth OK (user: %s)", user.get("username", "?"))
                else:
                    log.warning(
                        "SG token may be invalid — currentUser returned null. "
                        "SG search tools will fail with 403."
                    )
                    self.token = ""  # Disable SG tools
        except (urllib.error.URLError, Exception) as e:
            log.warning("SG token validation failed: %s. SG search tools disabled.", e)
            self.token = ""  # Disable SG tools

    def keyword_search(self, query: str, max_results: int = 50) -> str:
        """Run a keyword search and return formatted results."""
        import urllib.request
        import urllib.error

        gql = """query KeywordSearch($query: String!) {
            search(query: $query, version: V2) {
                results {
                    results {
                        ... on FileMatch {
                            repository { name }
                            file { path }
                            lineMatches { lineNumber preview }
                        }
                    }
                }
            }
        }"""
        full_query = f"{query} count:{max_results}"
        body = json.dumps({"query": gql, "variables": {"query": full_query}}).encode()
        req = urllib.request.Request(
            f"{self.url.rstrip('/')}/.api/graphql",
            data=body,
            headers=self._headers(),
        )
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                data = json.loads(resp.read())
        except (urllib.error.URLError, Exception) as e:
            return f"Search error: {e}"

        results = data.get("data", {}).get("search", {}).get("results", {}).get("results", [])
        lines = []
        for r in results[:max_results]:
            repo = r.get("repository", {}).get("name", "?")
            path = r.get("file", {}).get("path", "?")
            matches = r.get("lineMatches", [])
            for m in matches[:3]:
                ln = m.get("lineNumber", 0)
                preview = m.get("preview", "").strip()[:200]
                lines.append(f"{repo}:{path}:{ln}: {preview}")
        return "\n".join(lines) if lines else "No results found."

    def deep_search(self, query: str, repos: List[str] = None) -> str:
        """Run a deep search query. Returns formatted summary."""
        # Deep search uses the streaming chat API which is complex.
        # Fallback: use NLS (natural language search) via keyword endpoint
        # with patternType:keyword for linguistic matching.
        repo_filter = ""
        if repos:
            repo_clauses = " ".join(f"repo:{r}" for r in repos)
            repo_filter = f"{repo_clauses} "
        full_query = f"{repo_filter}{query} patternType:keyword"
        return self.keyword_search(full_query, max_results=100)


def execute_deep_search(query: str, repos: List[str] = None, sg: "SourcegraphClient" = None) -> str:
    """Execute a deep search tool call."""
    if not sg or not sg.token:
        return "Deep search unavailable: no Sourcegraph token configured."
    return sg.deep_search(query, repos or [])


def execute_sourcegraph_search(query: str, sg: "SourcegraphClient" = None) -> str:
    """Execute a Sourcegraph keyword search tool call."""
    if not sg or not sg.token:
        return "Sourcegraph search unavailable: no token configured."
    return sg.keyword_search(query)

# ---------------------------------------------------------------------------
# Tool definitions for the agent
# ---------------------------------------------------------------------------

TOOLS = [
    {
        "name": "run_shell",
        "description": (
            "Execute a read-only shell command against the local repository. "
            "Allowed commands: grep, rg (ripgrep), find, wc, tree, head, tail, "
            "sort, uniq, file, dirname, basename, ls, stat. "
            "Commands that modify files (rm, mv, cp, git commit, etc.) are blocked. "
            "Output is truncated to 10000 characters."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string",
                    "description": "The shell command to execute."
                },
                "cwd": {
                    "type": "string",
                    "description": "Working directory (defaults to repo root)."
                },
            },
            "required": ["command"],
        },
    },
    {
        "name": "read_file",
        "description": (
            "Read the contents of a file. Returns up to 500 lines by default. "
            "Use start_line/end_line for targeted reading of large files."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string",
                    "description": "Absolute or repo-relative file path."
                },
                "start_line": {
                    "type": "integer",
                    "description": "1-based start line (optional)."
                },
                "end_line": {
                    "type": "integer",
                    "description": "1-based end line (optional)."
                },
            },
            "required": ["path"],
        },
    },
    {
        "name": "list_directory",
        "description": (
            "List files and subdirectories. Returns names only, one per line. "
            "Use pattern for glob filtering (e.g., '*.go', '*.java')."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string",
                    "description": "Directory path to list."
                },
                "pattern": {
                    "type": "string",
                    "description": "Glob pattern filter (e.g., '*.py')."
                },
                "recursive": {
                    "type": "boolean",
                    "description": "If true, list recursively (max 2000 entries)."
                },
            },
            "required": ["path"],
        },
    },
    {
        "name": "search_imports",
        "description": (
            "Find all source files that import a specific package or module. "
            "Language-aware: handles Go imports, Java imports, Python imports, "
            "C/C++ #include, Rust use/mod, JS/TS import/require. "
            "Returns file paths with matching import lines."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "repo_path": {
                    "type": "string",
                    "description": "Root directory of the repository to search."
                },
                "import_pattern": {
                    "type": "string",
                    "description": (
                        "The package/module to search for "
                        "(e.g., 'k8s.io/apimachinery/pkg/runtime')."
                    ),
                },
                "language": {
                    "type": "string",
                    "description": (
                        "Programming language hint: go, java, python, c, cpp, "
                        "rust, javascript, typescript. Auto-detected if omitted."
                    ),
                },
            },
            "required": ["repo_path", "import_pattern"],
        },
    },
    {
        "name": "find_symbols",
        "description": (
            "Find definitions of functions, classes, methods, interfaces, and "
            "structs in source files using regex-based pattern matching. "
            "Returns file paths with symbol name and line number."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "repo_path": {
                    "type": "string",
                    "description": "Root directory of the repository to search."
                },
                "symbol_name": {
                    "type": "string",
                    "description": "Name of the symbol to find (function, class, etc.)."
                },
                "language": {
                    "type": "string",
                    "description": "Language hint for pattern selection."
                },
            },
            "required": ["repo_path", "symbol_name"],
        },
    },
]

# Allowlist for shell commands (security)
ALLOWED_COMMANDS = {
    "grep", "rg", "find", "wc", "tree", "head", "tail",
    "sort", "uniq", "file", "dirname", "basename", "ls", "stat",
    "cat", "awk", "sed", "xargs", "echo", "true", "test",
}

# ---------------------------------------------------------------------------
# Tool execution
# ---------------------------------------------------------------------------


def _validate_shell_command(command: str) -> Optional[str]:
    """Check that a shell command uses only allowed executables.

    Returns an error message if blocked, None if OK.
    """
    # Extract the first word (the executable)
    try:
        parts = shlex.split(command)
    except ValueError:
        parts = command.split()
    if not parts:
        return "Empty command"

    # Handle pipes: check each segment
    segments = command.split("|")
    for seg in segments:
        seg = seg.strip()
        if not seg:
            continue
        try:
            seg_parts = shlex.split(seg)
        except ValueError:
            seg_parts = seg.split()
        if not seg_parts:
            continue
        exe = seg_parts[0]
        # Strip path prefix
        exe = os.path.basename(exe)
        if exe not in ALLOWED_COMMANDS:
            return f"Command '{exe}' is not in the allowlist: {sorted(ALLOWED_COMMANDS)}"
    return None


def execute_run_shell(command: str, cwd: str = "") -> str:
    """Execute a read-only shell command."""
    err = _validate_shell_command(command)
    if err:
        return f"BLOCKED: {err}"
    try:
        result = subprocess.run(
            command, shell=True,
            capture_output=True, text=True,
            timeout=TOOL_TIMEOUT_SEC,
            cwd=cwd or None,
        )
        output = result.stdout
        if result.stderr:
            output += f"\n[stderr]: {result.stderr[:2000]}"
        if result.returncode != 0 and not output.strip():
            output = f"[exit code {result.returncode}]"
        return output[:10000]
    except subprocess.TimeoutExpired:
        return f"[TIMEOUT after {TOOL_TIMEOUT_SEC}s]"
    except Exception as e:
        return f"[ERROR]: {e}"


def execute_read_file(
    path: str, start_line: int = 0, end_line: int = 0
) -> str:
    """Read file contents."""
    p = Path(path)
    if not p.exists():
        return f"File not found: {path}"
    if not p.is_file():
        return f"Not a file: {path}"
    try:
        lines = p.read_text(errors="replace").splitlines()
    except Exception as e:
        return f"Error reading {path}: {e}"

    if start_line > 0:
        start_idx = max(0, start_line - 1)
        end_idx = end_line if end_line > 0 else start_idx + 500
        lines = lines[start_idx:end_idx]
        offset = start_idx + 1
    else:
        if len(lines) > 500:
            lines = lines[:500]
            lines.append(f"... [truncated at 500 lines, total {len(lines)} lines]")
        offset = 1

    numbered = [f"{i + offset}: {line}" for i, line in enumerate(lines)]
    return "\n".join(numbered)


def execute_list_directory(
    path: str, pattern: str = "", recursive: bool = False
) -> str:
    """List directory contents."""
    p = Path(path)
    if not p.exists():
        return f"Directory not found: {path}"
    if not p.is_dir():
        return f"Not a directory: {path}"

    try:
        if recursive:
            if pattern:
                entries = sorted(p.rglob(pattern))
            else:
                entries = sorted(p.rglob("*"))
            entries = entries[:2000]
        else:
            if pattern:
                entries = sorted(p.glob(pattern))
            else:
                entries = sorted(p.iterdir())

        lines = []
        for e in entries:
            rel = e.relative_to(p)
            suffix = "/" if e.is_dir() else ""
            lines.append(f"{rel}{suffix}")
        if len(lines) >= 2000:
            lines.append("... [truncated at 2000 entries]")
        return "\n".join(lines) if lines else "[empty directory]"
    except Exception as e:
        return f"Error: {e}"


def execute_search_imports(
    repo_path: str, import_pattern: str, language: str = ""
) -> str:
    """Language-aware import search using ripgrep."""
    lang = language.lower() if language else ""
    pattern = re.escape(import_pattern)

    # Build language-specific import regex patterns
    rg_patterns = []
    if lang in ("go", ""):
        rg_patterns.append(f'"({pattern}[^"]*)"')
    if lang in ("java", ""):
        rg_patterns.append(f"import\\s+.*{pattern}")
    if lang in ("python", ""):
        rg_patterns.append(f"(from|import)\\s+{pattern}")
    if lang in ("c", "cpp", ""):
        rg_patterns.append(f'#include\\s+[<"]{pattern}')
    if lang in ("rust", ""):
        rg_patterns.append(f"use\\s+{pattern}")
    if lang in ("javascript", "typescript", ""):
        rg_patterns.append(f"(import|require).*{pattern}")

    # Use the most specific pattern or combine
    if lang:
        search_pattern = rg_patterns[0] if rg_patterns else pattern
    else:
        search_pattern = "|".join(rg_patterns) if rg_patterns else pattern

    cmd = f"rg -n --no-heading '{search_pattern}' {shlex.quote(repo_path)}"
    try:
        result = subprocess.run(
            cmd, shell=True, capture_output=True, text=True,
            timeout=TOOL_TIMEOUT_SEC,
        )
        output = result.stdout[:10000]
        if not output.strip():
            # Fallback to simpler grep
            cmd2 = f"rg -n --no-heading '{pattern}' {shlex.quote(repo_path)}"
            result2 = subprocess.run(
                cmd2, shell=True, capture_output=True, text=True,
                timeout=TOOL_TIMEOUT_SEC,
            )
            output = result2.stdout[:10000]
        return output if output.strip() else f"No imports matching '{import_pattern}' found."
    except subprocess.TimeoutExpired:
        return f"[TIMEOUT searching for imports in {repo_path}]"
    except Exception as e:
        return f"[ERROR]: {e}"


def execute_find_symbols(
    repo_path: str, symbol_name: str, language: str = ""
) -> str:
    """Find symbol definitions using regex patterns."""
    name = re.escape(symbol_name)
    patterns = [
        # Go: func, type, interface
        f"(func|type|interface)\\s+{name}\\b",
        # Python: def, class
        f"(def|class)\\s+{name}\\b",
        # Java/C++: access modifiers + name
        f"(public|private|protected|static|abstract|final)?\\s*(class|interface|enum|struct|void|int|long|String|boolean)\\s+{name}\\b",
        # Rust: fn, struct, trait, impl, enum
        f"(fn|struct|trait|impl|enum|type|const)\\s+{name}\\b",
        # Generic assignment/definition
        f"\\b{name}\\s*[=:(]",
    ]
    combined = "|".join(f"({p})" for p in patterns)
    cmd = f"rg -n --no-heading -e '{combined}' {shlex.quote(repo_path)}"
    try:
        result = subprocess.run(
            cmd, shell=True, capture_output=True, text=True,
            timeout=TOOL_TIMEOUT_SEC,
        )
        return result.stdout[:10000] if result.stdout.strip() else f"No definition of '{symbol_name}' found."
    except subprocess.TimeoutExpired:
        return f"[TIMEOUT searching for {symbol_name}]"
    except Exception as e:
        return f"[ERROR]: {e}"


def get_tools_for_backend(backend: str) -> List[Dict]:
    """Return the tool definitions available for a given backend."""
    local_tools = list(TOOLS)  # run_shell, read_file, list_directory, search_imports, find_symbols
    sg_tools = [DEEPSEARCH_TOOL, KEYWORD_SEARCH_TOOL]
    if backend == "local":
        return local_tools
    elif backend == "deepsearch":
        return sg_tools
    else:  # hybrid
        return local_tools + sg_tools


def dispatch_tool(
    name: str, input_args: Dict[str, Any], sg: Optional["SourcegraphClient"] = None
) -> str:
    """Dispatch a tool call to the appropriate handler."""
    if name == "run_shell":
        return execute_run_shell(
            input_args.get("command", ""),
            input_args.get("cwd", ""),
        )
    elif name == "read_file":
        # Coerce start_line/end_line to int — models sometimes pass strings
        def _to_int(val: Any, default: int = 0) -> int:
            if isinstance(val, int):
                return val
            try:
                return int(val)
            except (TypeError, ValueError):
                return default
        return execute_read_file(
            input_args.get("path", ""),
            _to_int(input_args.get("start_line", 0)),
            _to_int(input_args.get("end_line", 0)),
        )
    elif name == "list_directory":
        return execute_list_directory(
            input_args.get("path", ""),
            input_args.get("pattern", ""),
            input_args.get("recursive", False),
        )
    elif name == "search_imports":
        return execute_search_imports(
            input_args.get("repo_path", ""),
            input_args.get("import_pattern", ""),
            input_args.get("language", ""),
        )
    elif name == "find_symbols":
        return execute_find_symbols(
            input_args.get("repo_path", ""),
            input_args.get("symbol_name", ""),
            input_args.get("language", ""),
        )
    elif name == "deep_search":
        return execute_deep_search(
            input_args.get("query", ""),
            input_args.get("repos", []),
            sg=sg,
        )
    elif name == "sourcegraph_search":
        return execute_sourcegraph_search(
            input_args.get("query", ""),
            sg=sg,
        )
    else:
        return f"Unknown tool: {name}"


# ---------------------------------------------------------------------------
# Repo cloning and cache
# ---------------------------------------------------------------------------


def get_cache_dir() -> Path:
    """Get the repo clone cache directory."""
    d = Path(os.environ.get("CCB_REPO_CACHE", str(DEFAULT_CACHE_DIR)))
    d.mkdir(parents=True, exist_ok=True)
    return d


def clone_repo(mirror_slug: str, cache_dir: Optional[Path] = None) -> Path:
    """Clone a repo to the cache. Skip if already exists.

    Args:
        mirror_slug: e.g. "sg-evals/kubernetes--v1.32.0"
        cache_dir: Override cache directory.

    Returns:
        Path to the cloned repo.
    """
    cache = cache_dir or get_cache_dir()
    # Use the slug as directory name (replace / with __)
    dir_name = mirror_slug.replace("/", "__")
    repo_dir = cache / dir_name

    if repo_dir.exists() and (repo_dir / ".git").exists():
        log.debug("Cache hit: %s", repo_dir)
        return repo_dir

    url = f"https://github.com/{mirror_slug}.git"
    log.info("Cloning %s -> %s", url, repo_dir)
    repo_dir.mkdir(parents=True, exist_ok=True)
    try:
        subprocess.run(
            ["git", "clone", "--depth", "1", url, str(repo_dir)],
            check=True, capture_output=True, text=True,
            timeout=600,
        )
    except subprocess.CalledProcessError as e:
        log.error("Clone failed for %s: %s", mirror_slug, e.stderr[:500])
        raise
    return repo_dir


def ensure_repos_cloned(
    repo_specs: List[Dict[str, str]], cache_dir: Optional[Path] = None
) -> Dict[str, Path]:
    """Clone all repos and return a mapping of logical_name -> local_path."""
    result = {}
    for spec in repo_specs:
        full_name = spec.get("full_name", "")
        logical = spec.get("logical_name", full_name)
        try:
            path = clone_repo(full_name, cache_dir)
            result[logical] = path
            result[full_name] = path  # also map by full_name
        except Exception as e:
            log.warning("Failed to clone %s: %s", full_name, e)
    return result


# ---------------------------------------------------------------------------
# Task discovery
# ---------------------------------------------------------------------------


def find_project_root() -> Path:
    """Walk up from this script to find the CodeContextBench root."""
    p = Path(__file__).resolve().parent
    while p != p.parent:
        if (p / "benchmarks").is_dir() and (p / "fixtures").is_dir():
            return p
        p = p.parent
    return Path(__file__).resolve().parent.parent


def discover_tasks(
    suite: str = "",
    task_dir: str = "",
    sdlc_all: bool = False,
    mcp_all: bool = False,
) -> List[Path]:
    """Discover task directories to process."""
    root = find_project_root()
    benchmarks = root / "benchmarks"

    if task_dir:
        p = Path(task_dir)
        if not p.is_absolute():
            p = root / p
        return [p] if p.is_dir() else []

    suites = []
    if sdlc_all:
        suites = SDLC_SUITES
    elif mcp_all:
        suites = MCP_UNIQUE_SUITES
    elif suite:
        suites = [suite]
    else:
        suites = SDLC_SUITES + MCP_UNIQUE_SUITES

    tasks = []
    for s in suites:
        suite_dir = benchmarks / s
        if not suite_dir.is_dir():
            continue
        for task in sorted(suite_dir.iterdir()):
            if task.is_dir() and not task.name.startswith("."):
                tasks.append(task)
    return tasks


def load_task_context(task_dir: Path) -> Dict[str, Any]:
    """Load all relevant context from a task directory.

    Returns dict with: instruction, seed_prompt, repo_set_id, check_types,
    repo_specs, existing_oracle, suite_name.
    """
    root = find_project_root()
    ctx: Dict[str, Any] = {
        "task_dir": str(task_dir),
        "task_name": task_dir.name,
        "suite_name": task_dir.parent.name,
    }

    # Read instruction.md
    instruction = task_dir / "instruction.md"
    if instruction.exists():
        ctx["instruction"] = instruction.read_text()[:8000]
    else:
        ctx["instruction"] = ""

    # Try task_spec.json (MCP-unique tasks)
    task_spec_path = task_dir / "tests" / "task_spec.json"
    if not task_spec_path.exists():
        task_spec_path = task_dir / "task_spec.json"

    if task_spec_path.exists():
        try:
            spec = json.loads(task_spec_path.read_text())
            ctx["seed_prompt"] = spec.get("prd", {}).get("seed_prompt", "")
            ctx["repo_set_id"] = spec.get("artifacts", {}).get("repo_set_id", "")
            ctx["check_types"] = [
                c.get("type", "") for c in spec.get("evaluation", {}).get("checks", [])
            ]
        except (json.JSONDecodeError, KeyError):
            pass

    # Try to get repo info from Dockerfile
    dockerfile = task_dir / "environment" / "Dockerfile"
    if dockerfile.exists():
        ctx["repo_urls"] = _extract_clone_urls(dockerfile.read_text())

    # Load repo set fixture if available
    repo_set_id = ctx.get("repo_set_id", "")
    if repo_set_id:
        fixture_path = root / "fixtures" / "repo_sets" / f"{repo_set_id}.json"
        if fixture_path.exists():
            try:
                ctx["repo_fixture"] = json.loads(fixture_path.read_text())
            except json.JSONDecodeError:
                pass

    # Load existing oracle for comparison
    oracle_path = task_dir / "tests" / "oracle_answer.json"
    if oracle_path.exists():
        try:
            ctx["existing_oracle"] = json.loads(oracle_path.read_text())
        except json.JSONDecodeError:
            pass

    gt_path = task_dir / "tests" / "ground_truth.json"
    if gt_path.exists():
        try:
            ctx["existing_ground_truth"] = json.loads(gt_path.read_text())
        except json.JSONDecodeError:
            pass

    return ctx


def _extract_clone_urls(dockerfile_content: str) -> List[Dict[str, str]]:
    """Extract git clone URLs from a Dockerfile."""
    results = []
    for match in re.finditer(
        r"git\s+clone\s+(?:--depth\s+\d+\s+)?(\S+?)(?:\.git)?\s+(\S+)",
        dockerfile_content,
    ):
        url = match.group(1)
        target = match.group(2)
        # Extract mirror slug from URL
        m = re.search(r"github\.com/(.+?)(?:\.git)?$", url)
        slug = m.group(1) if m else url
        results.append({"url": url, "slug": slug, "target": target})
    return results


# ---------------------------------------------------------------------------
# Agent interaction
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Unified Curator System Prompt
# ---------------------------------------------------------------------------
# Replaces the previous 6 backend-specific prompts (SDK x3 + CLI x3) and
# SYSTEM_PROMPT_SUFFIX. All backends and modes share this single prompt,
# parameterized by {tool_description}.

CURATOR_SYSTEM_PROMPT = """\
# Role
You are a benchmark curator agent for CodeContextBench. Your task is to
identify all source files a developer would need to READ or MODIFY to
understand and solve a software engineering task, then annotate each file
with the specific line ranges that are relevant.

You are NOT solving the task. You are producing the authoritative ground
truth that allows us to measure whether other agents solved it correctly.

# Calibration Standard
Your behavior is calibrated against ContextBench's human-annotated dataset
(1,136 SWE-bench tasks). Human annotators include BOTH modification files
AND understanding/context files (tests, configs, dependencies). You must
do the same.

# Inclusion Rule
Include a file if a skilled developer MUST read it to correctly solve the task:
- Files that need code changes (edits/patches)
- Test files that reveal the bug or define expected behavior
- Dependency implementations needed to understand the call chain
- Configuration files that constrain the solution
- Type definitions, headers, or interfaces needed for correctness

Do NOT include files discovered incidentally (e.g., via transitive imports)
that are not needed to understand the core issue.

# Size Calibration (from ContextBench empirical distribution)
- Small tasks: 1-3 files (narrow, focused issues)
- Medium tasks: 3-8 files (multi-component understanding)
- Large tasks: 8-15+ files (complex dependencies or broad refactors)
Most tasks need 3-5 files. Err toward recall over precision — missing a
relevant file is worse than including an extra one.

# Tools Available
{tool_description}

# Strategy
1. Parse the task carefully. Identify key entities (packages, types, functions).
2. Explore broadly first — understand the repo structure and locate entry points.
3. For each candidate file, READ it to identify the specific line ranges relevant
   to the task. Record start_line and end_line for each relevant section.
4. Classify each included file as either:
   - "edit": file that would need modification to solve the task
   - "context": file needed for understanding but not modified
5. For multi-repo tasks, search ALL repos, not just the most obvious one.
6. Cross-validate: verify every file you include by reading it directly.
   Do not include files based solely on search result summaries.

# Output Format
When done, output a JSON object inside a ```json fenced block:
```json
{{
  "files": ["repo-relative/path/to/file.ext", ...],
  "expected_edit_files": ["repo-relative/path/to/file.ext", ...],
  "symbols": [
    {{"file": "path", "symbol": "ClassName.method_name", "repo": null}}
  ],
  "chunks": [
    {{"file": "path", "line_start": 10, "line_end": 40, "annotation": "why this range is relevant"}}
  ],
  "dependency_chain": ["path1", "path2", ...],
  "text": "Brief explanation of methodology and findings."
}}
```

Rules:
- "files" MUST be repo-relative path strings (e.g. "src/main.py"), NOT dicts.
- "expected_edit_files" is a SUBSET of "files": only files a fix would modify.
- "chunks" MUST have at least one entry per file in "files".
  Each chunk identifies the specific function, class, or block that is relevant.
- "symbols" lists key function/class definitions you identified.
- "dependency_chain" is the ordered sequence of files in the call/import chain.
- For multi-repo tasks, prefix paths with "repo_name::" when needed.
IMPORTANT: Output the JSON as a fenced code block with ```json markers.
"""


def _tool_description_for_backend(backend: str, cli_mode: bool = False) -> str:
    """Return tool description text for the curator system prompt."""
    if cli_mode:
        local = (
            "Local tools:\n"
            "- Bash (read-only): run grep, rg (ripgrep), find, ls, wc, and other read-only shell commands\n"
            "- Read: read source file contents\n"
            "- Glob: find files by glob patterns (e.g., '**/*.py')\n"
            "- Grep: search file contents with regex patterns"
        )
        ds = (
            "Sourcegraph Deep Search (via Bash — MUST USE):\n"
            "Run: bash /home/stephanie_jarmak/CodeContextBench/scripts/ds_wrapper.sh \"your question here\"\n"
            "CRITICAL: Always include the repository name in your query.\n"
            "Examples:\n"
            "- \"What files implement RBAC escalation checks in kubernetes/kubernetes?\"\n"
            "- \"Where is the ProducerBatch class defined in apache/kafka?\"\n"
            "Deep Search takes 30-60 seconds. Use it for broad exploration, architecture\n"
            "questions, dependency tracing, and finding implementations across repos."
        )
        sg_kw = "- mcp__sourcegraph__sg_keyword_search: keyword/regex code search with filters"

        if backend == "local":
            return f"{local}\n\nYou do NOT have access to any search engine, web API, or code search service."
        elif backend == "deepsearch":
            return f"{ds}\n{sg_kw}"
        else:  # hybrid
            return f"{local}\n\n{ds}\n{sg_kw}"
    else:
        # SDK mode tools
        local = (
            "Local tools:\n"
            "- run_shell: grep, ripgrep, find, and other read-only shell commands\n"
            "- read_file: read source file contents\n"
            "- list_directory: explore directory trees\n"
            "- search_imports: language-aware import/include search\n"
            "- find_symbols: find function/class/interface definitions"
        )
        sg = (
            "Sourcegraph tools:\n"
            "- deep_search: AI-powered semantic code search across repositories\n"
            "- sourcegraph_search: keyword/regex code search with filters"
        )

        if backend == "local":
            return f"{local}\n\nYou do NOT have access to any search engine, web API, or code search service."
        elif backend == "deepsearch":
            return sg
        else:  # hybrid
            return f"{local}\n\n{sg}"

# CLI_SYSTEM_PROMPTS and SYSTEM_PROMPTS removed — replaced by unified
# CURATOR_SYSTEM_PROMPT above. Both SDK and CLI modes use the same prompt
# template, parameterized via _tool_description_for_backend().


def run_agent_cli(
    ctx: Dict[str, Any],
    repo_paths: Dict[str, Path],
    model: str = DEFAULT_MODEL,
    backend: str = "hybrid",
    verbose: bool = False,
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Run the retrieval agent via Claude CLI (subscription billing).

    Uses the ``claude`` CLI in ``--print --output-format json`` mode.
    Claude CLI handles the tool loop internally and bills through OAuth
    subscription rather than API key billing.

    Returns:
        (oracle_result, metadata) — same interface as run_agent().
    """
    system = CURATOR_SYSTEM_PROMPT.format(
        tool_description=_tool_description_for_backend(backend, cli_mode=True),
    )
    user_msg = build_user_message(ctx, repo_paths)

    # -- Determine allowed tools based on backend --
    local_tools = ["Bash(read-only:true)", "Read", "Glob", "Grep"]
    # Deep Search needs Bash (not read-only) to call ds_wrapper.sh
    ds_tools = ["Bash", "Read", "Glob", "Grep"]
    sg_tools = [
        "mcp__sourcegraph__sg_keyword_search",
    ]

    if backend == "local":
        allowed_tools = local_tools
    elif backend == "deepsearch":
        allowed_tools = ["Bash"] + sg_tools
    else:  # hybrid
        allowed_tools = ds_tools + sg_tools

    # -- Write system prompt to temp file (avoids ARG_MAX) --
    sys_prompt_file = tempfile.NamedTemporaryFile(
        mode="w", suffix=".txt", prefix="ccb_sys_", delete=False,
    )
    sys_prompt_file.write(system)
    sys_prompt_file.close()

    # -- Generate MCP config for SG if needed --
    mcp_config_path = None
    if backend in ("deepsearch", "hybrid"):
        sg_token = os.environ.get("SOURCEGRAPH_ACCESS_TOKEN", "")
        sg_url = os.environ.get("SOURCEGRAPH_URL", "https://sourcegraph.sourcegraph.com")
        sg_url = sg_url.rstrip("/")
        if sg_token:
            mcp_config = {
                "mcpServers": {
                    "sourcegraph": {
                        "type": "http",
                        "url": f"{sg_url}/.api/mcp/v1",
                        "headers": {"Authorization": f"token {sg_token}"},
                    }
                }
            }
            mcp_file = tempfile.NamedTemporaryFile(
                mode="w", suffix=".json", prefix="ccb_mcp_", delete=False,
            )
            json.dump(mcp_config, mcp_file)
            mcp_file.close()
            mcp_config_path = mcp_file.name
        else:
            log.warning("SOURCEGRAPH_ACCESS_TOKEN not set; SG/Deep Search tools unavailable")
            # Fall back to local-only tools (no Deep Search without token)
            allowed_tools = local_tools

    # -- Build CLI command --
    cmd = [
        "claude",
        "-p", user_msg,
        "--output-format", "json",
        "--model", model,
        "--append-system-prompt", system,
        "--allowedTools", ",".join(allowed_tools),
        "--dangerously-skip-permissions",
    ]
    if mcp_config_path:
        cmd.extend(["--mcp-config", mcp_config_path])

    # -- Environment: unset CLAUDECODE to avoid nesting detection --
    env = {k: v for k, v in os.environ.items() if k != "CLAUDECODE"}
    # Ensure SRC_ACCESS_TOKEN is set for ds_wrapper.sh (Deep Search)
    if "SRC_ACCESS_TOKEN" not in env:
        sg_token = env.get("SOURCEGRAPH_ACCESS_TOKEN", "")
        if sg_token:
            env["SRC_ACCESS_TOKEN"] = sg_token

    if verbose:
        log.info("CLI cmd: claude -p <user_msg> --model %s --allowedTools %s",
                 model, ",".join(allowed_tools))

    start_time = time.time()

    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, env=env,
            timeout=TASK_TIMEOUT_SEC + 60,  # extra margin for CLI overhead
        )
    except subprocess.TimeoutExpired:
        log.error("Claude CLI timed out after %ds", TASK_TIMEOUT_SEC + 60)
        return (
            {"files": [], "text": "CLI timeout"},
            _cli_error_metadata(model, backend, start_time),
        )
    finally:
        # Clean up temp files
        try:
            os.unlink(sys_prompt_file.name)
        except OSError:
            pass
        if mcp_config_path:
            try:
                os.unlink(mcp_config_path)
            except OSError:
                pass

    if result.returncode != 0:
        log.error("Claude CLI failed (rc=%d): %s", result.returncode,
                  (result.stderr or result.stdout or "")[:500])
        return (
            {"files": [], "text": f"CLI error (rc={result.returncode})"},
            _cli_error_metadata(model, backend, start_time),
        )

    # -- Parse JSON output --
    try:
        cli_output = json.loads(result.stdout)
    except (json.JSONDecodeError, ValueError) as e:
        log.error("Failed to parse CLI JSON output: %s", e)
        log.debug("Raw stdout: %s", result.stdout[:1000])
        return (
            {"files": [], "text": "CLI output parse error"},
            _cli_error_metadata(model, backend, start_time),
        )

    # -- Extract oracle from result text --
    result_text = cli_output.get("result", "")
    oracle_result = _extract_json_from_text(result_text)
    if oracle_result is None:
        log.warning("Could not extract oracle JSON from CLI result text")
        oracle_result = {"files": [], "text": "No oracle JSON in CLI output."}

    # -- Build metadata from CLI output --
    elapsed = time.time() - start_time
    usage = cli_output.get("usage", {})
    input_tokens = usage.get("input_tokens", 0)
    output_tokens = usage.get("output_tokens", 0)
    cache_read = usage.get("cache_read_input_tokens", 0)
    cache_create = usage.get("cache_creation_input_tokens", 0)

    metadata = {
        "generator": "context_retrieval_agent_cli",
        "model": model,
        "backend": backend,
        "input_tokens": input_tokens + cache_read + cache_create,
        "output_tokens": output_tokens,
        "tool_calls": cli_output.get("num_turns", 1) - 1,  # turns includes final
        "elapsed_sec": round(elapsed, 1),
        "cost_usd": round(cli_output.get("total_cost_usd", 0.0), 4),
        "num_turns": cli_output.get("num_turns", 0),
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "cli_mode": True,
    }

    if verbose:
        log.info("  CLI done: %d turns, $%.4f, %.1fs",
                 metadata["num_turns"], metadata["cost_usd"], elapsed)

    return oracle_result, metadata


def _cli_error_metadata(model: str, backend: str, start_time: float) -> Dict[str, Any]:
    """Build error metadata for failed CLI runs."""
    return {
        "generator": "context_retrieval_agent_cli",
        "model": model,
        "backend": backend,
        "input_tokens": 0,
        "output_tokens": 0,
        "tool_calls": 0,
        "elapsed_sec": round(time.time() - start_time, 1),
        "cost_usd": 0.0,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "cli_mode": True,
        "error": True,
    }


# PRUNE_PROMPT and prune_oracle_cli() removed — pruning guidance is now
# integrated into the unified CURATOR_SYSTEM_PROMPT. The curator prompt
# instructs the agent to classify files as "edit" vs "context" and
# exclude files discovered incidentally.


# ---------------------------------------------------------------------------
# Phase 0: Task parsing for curator
# ---------------------------------------------------------------------------


def parse_task_for_curator(task_dir: Path) -> Dict[str, Any]:
    """Phase 0: Parse task artifacts to build structured context for the curator.

    Enriches load_task_context() output with:
      - task_type: 'sdlc' or 'mcp_unique'
      - is_multi_repo: bool
      - test_sh_diff_targets: files referenced in git diff commands in test.sh
      - test_sh_file_patterns: general file references in test.sh
    """
    ctx = load_task_context(task_dir)
    suite = ctx.get("suite_name", "")
    ctx["task_type"] = "mcp_unique" if suite.startswith("ccb_mcp_") else "sdlc"

    # Detect multi-repo from Dockerfile env vars or fixture
    ctx["is_multi_repo"] = bool(ctx.get("repo_fixture", {}).get("repos", []))
    if not ctx["is_multi_repo"]:
        docker_sg = task_dir / "environment" / "Dockerfile.sg_only"
        if docker_sg.exists():
            text = docker_sg.read_text()
            ctx["is_multi_repo"] = "SOURCEGRAPH_REPOS" in text

    # Parse test.sh for expected edit targets
    test_sh = task_dir / "tests" / "test.sh"
    ctx["test_sh_file_patterns"] = []
    ctx["test_sh_diff_targets"] = []
    if test_sh.exists():
        test_text = test_sh.read_text()
        # Extract git diff file targets (e.g. git diff -- path/to/file)
        for m in re.finditer(r'git\s+diff.*?--\s+([\w/._-]+)', test_text):
            target = m.group(1).strip()
            if target and not target.startswith("-"):
                ctx["test_sh_diff_targets"].append(target)
        # Extract general file references (cat, grep, test -f)
        for m in re.finditer(r'(?:cat|grep|test\s+-[ef])\s+["\']?(/?\w[\w/._-]+)', test_text):
            ctx["test_sh_file_patterns"].append(m.group(1))

    return ctx


# ---------------------------------------------------------------------------
# Schema Converters: agent output → ground_truth.json / oracle_answer.json
# ---------------------------------------------------------------------------


def _infer_primary_repo(ctx: Dict[str, Any]) -> str:
    """Infer the primary repository name from task context."""
    # From Dockerfile env vars
    docker_envs = ctx.get("docker_env_vars", {})
    repo_name = docker_envs.get("SOURCEGRAPH_REPO_NAME", "")
    if repo_name:
        return repo_name
    # From clone URLs
    urls = ctx.get("repo_urls", [])
    if urls and isinstance(urls[0], dict):
        return urls[0].get("slug", urls[0].get("name", ""))
    if urls and isinstance(urls[0], str):
        return urls[0]
    return ""


def _convert_to_ir_schema(
    raw_oracle: Dict[str, Any],
    ctx: Dict[str, Any],
) -> Dict[str, Any]:
    """Convert agent output to the IR pipeline's ground_truth.json schema.

    Target format matches schemas/retrieval_events_schema.json ground_truth block:
      {files: [string], symbols: [{file, symbol, repo?}], expected_edit_files: [string],
       chunks: [{file, line_start, line_end, annotation?}]}

    Handles both new format (files as strings) and legacy (files as {repo, path} dicts).
    """
    # Normalize files to plain string paths
    files = []
    for f in raw_oracle.get("files", []):
        if isinstance(f, str):
            files.append(f)
        elif isinstance(f, dict):
            repo = f.get("repo", "")
            path = f.get("path", "")
            if ctx.get("is_multi_repo") and repo:
                clean = repo.replace("sg-evals/", "")
                if "--" in clean:
                    clean = clean.split("--")[0]
                files.append(f"{clean}::{path}")
            else:
                files.append(path)
    # Deduplicate preserving order
    seen = set()
    deduped = []
    for f in files:
        if f and f not in seen:
            seen.add(f)
            deduped.append(f)
    files = deduped

    # Normalize expected_edit_files
    edit_files = []
    for f in raw_oracle.get("expected_edit_files", []):
        if isinstance(f, str):
            edit_files.append(f)
        elif isinstance(f, dict):
            edit_files.append(f.get("path", ""))
    edit_files = [f for f in edit_files if f]

    # If agent didn't produce expected_edit_files, infer from test.sh
    if not edit_files and ctx.get("test_sh_diff_targets"):
        edit_files = ctx["test_sh_diff_targets"]

    # Normalize symbols to {file, symbol, repo}
    symbols = []
    for s in raw_oracle.get("symbols", []):
        if isinstance(s, dict):
            symbols.append({
                "file": s.get("path", s.get("file", "")),
                "symbol": s.get("symbol", ""),
                "repo": s.get("repo") if ctx.get("is_multi_repo") else None,
            })

    # Normalize chunks
    chunks = []
    for c in raw_oracle.get("chunks", []):
        if isinstance(c, dict) and "file" in c and "line_start" in c and "line_end" in c:
            chunks.append({
                "file": c["file"],
                "line_start": c["line_start"],
                "line_end": c["line_end"],
                "annotation": c.get("annotation"),
            })

    # Build result
    result: Dict[str, Any] = {"files": files}
    if symbols:
        result["symbols"] = symbols
    if edit_files:
        # Determine confidence
        if ctx.get("test_sh_diff_targets") and edit_files:
            result["expected_edit_files"] = edit_files
            result["expected_edit_files_source"] = "curator_agent_verifier_analysis"
            result["expected_edit_files_confidence"] = "high"
        else:
            result["expected_edit_files"] = edit_files
            result["expected_edit_files_source"] = "curator_agent_inference"
            result["expected_edit_files_confidence"] = "medium"
    if chunks:
        result["chunks"] = chunks

    # Preserve dependency_chain if present
    chain = raw_oracle.get("dependency_chain", [])
    if chain:
        result["dependency_chain"] = chain

    return result


def _convert_to_oracle_schema(
    raw_oracle: Dict[str, Any],
    ctx: Dict[str, Any],
) -> Dict[str, Any]:
    """Convert agent output to oracle_answer.json format for MCP artifact verifier.

    Target format: {files: [{repo, path}], symbols: [{repo, path, symbol}],
                    chain: [...], text: str}
    """
    primary_repo = _infer_primary_repo(ctx)

    # Normalize files to {repo, path} dicts
    files = []
    for f in raw_oracle.get("files", []):
        if isinstance(f, dict) and "repo" in f and "path" in f:
            files.append(f)
        elif isinstance(f, str):
            if "::" in f:
                repo, path = f.split("::", 1)
                files.append({"repo": repo, "path": path})
            else:
                files.append({"repo": primary_repo, "path": f})

    # Normalize symbols
    symbols = []
    for s in raw_oracle.get("symbols", []):
        if isinstance(s, dict):
            symbols.append({
                "repo": s.get("repo", primary_repo),
                "path": s.get("path", s.get("file", "")),
                "symbol": s.get("symbol", ""),
            })

    # Normalize chain
    chain_raw = raw_oracle.get("chain", raw_oracle.get("dependency_chain", []))
    chain = []
    for c in chain_raw:
        if isinstance(c, dict):
            chain.append(c)
        elif isinstance(c, str):
            chain.append({"repo": primary_repo, "path": c, "symbol": ""})

    result: Dict[str, Any] = {"files": files}
    if symbols:
        result["symbols"] = symbols
    if chain:
        result["chain"] = chain
    result["text"] = raw_oracle.get("text", "")

    return result


def build_user_message(
    ctx: Dict[str, Any], repo_paths: Dict[str, Path]
) -> str:
    """Build the user message for the agent."""
    parts = []

    # Task description
    seed = ctx.get("seed_prompt", "")
    instruction = ctx.get("instruction", "")
    if seed:
        parts.append(f"## Task\n{seed}")
    elif instruction:
        parts.append(f"## Task\n{instruction[:4000]}")
    else:
        parts.append(f"## Task\nAnalyze task: {ctx.get('task_name', 'unknown')}")

    # Check types
    check_types = ctx.get("check_types", [])
    if check_types:
        parts.append(f"\n## Expected Output Types\n{', '.join(check_types)}")

    # Available repos — extract clean repo names for Deep Search queries
    repo_names = set()
    parts.append("\n## Repositories")
    if repo_paths:
        for name, path in sorted(repo_paths.items()):
            parts.append(f"- **{name}**: `{path}`")
            # Extract clean GitHub org/repo name for Deep Search
            # e.g. "sg-evals/kubernetes--v1.32.0" -> "kubernetes/kubernetes"
            # e.g. "django/django" -> "django/django"
            clean = name.replace("sg-evals/", "")
            # Strip version suffix: "kubernetes--v1.32.0" -> "kubernetes"
            if "--" in clean:
                clean = clean.split("--")[0]
            repo_names.add(clean)
    else:
        parts.append("- *(none cloned locally)*")

    # Infer repo names from task context if not available from paths
    instruction = ctx.get("instruction", "") + " " + ctx.get("seed_prompt", "")
    for pattern in re.findall(r'github\.com/([a-zA-Z0-9_-]+/[a-zA-Z0-9_.-]+)', instruction):
        repo_names.add(pattern.rstrip("."))

    if repo_names:
        parts.append(
            f"\n**Use these repo names in Deep Search queries**: "
            f"{', '.join(sorted(repo_names))}"
        )

    parts.append(
        "\n**IMPORTANT**: The repos listed above may NOT be complete. "
        "The task may involve additional repositories not cloned locally. "
        "Use Deep Search and keyword search to discover files "
        "in repositories beyond the local set. Do not assume local repos are exhaustive."
    )

    # Task type and verifier hints (from Phase 0 parsing)
    task_type = ctx.get("task_type", "")
    suite = ctx.get("suite_name", "")
    if suite:
        parts.append(f"\n## Suite: {suite}")
    if task_type:
        parts.append(f"Task type: {task_type}")

    # Verifier file targets — helps agent determine expected_edit_files
    diff_targets = ctx.get("test_sh_diff_targets", [])
    if diff_targets:
        parts.append(
            "\n## Verifier Targets (files checked by test.sh)\n"
            + "\n".join(f"- `{t}`" for t in diff_targets)
        )
        parts.append(
            "These files are checked by the verifier's `git diff` — they are likely "
            "the files that need modification (expected_edit_files)."
        )

    return "\n".join(parts)


def run_agent(
    ctx: Dict[str, Any],
    repo_paths: Dict[str, Path],
    client: "anthropic.Anthropic",
    model: str = DEFAULT_MODEL,
    backend: str = "hybrid",
    sg: Optional["SourcegraphClient"] = None,
    verbose: bool = False,
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Run the retrieval agent on a single task.

    Args:
        ctx: Task context from load_task_context().
        repo_paths: Mapping of repo name -> local path.
        client: Anthropic API client.
        model: Model to use (default: claude-sonnet-4-6).
        backend: Tool backend: "local", "deepsearch", or "hybrid".
        sg: SourcegraphClient for deepsearch/hybrid backends.
        verbose: Enable verbose logging.

    Returns:
        (oracle_result, metadata) where oracle_result is the JSON output
        and metadata has cost/timing info.
    """
    system = CURATOR_SYSTEM_PROMPT.format(
        tool_description=_tool_description_for_backend(backend, cli_mode=False),
    )
    tools = get_tools_for_backend(backend)
    user_msg = build_user_message(ctx, repo_paths)
    messages = [{"role": "user", "content": user_msg}]

    total_input_tokens = 0
    total_output_tokens = 0
    tool_call_count = 0
    start_time = time.time()

    for _turn in range(MAX_TOOL_CALLS + 5):
        elapsed = time.time() - start_time
        if elapsed > TASK_TIMEOUT_SEC:
            log.warning("Task timeout after %.0fs", elapsed)
            break
        if tool_call_count >= MAX_TOOL_CALLS:
            log.warning("Max tool calls (%d) reached", MAX_TOOL_CALLS)
            messages.append({
                "role": "user",
                "content": (
                    "You have used all available tool calls. Please provide "
                    "your final JSON answer now based on what you've found so far."
                ),
            })

        try:
            response = client.messages.create(
                model=model,
                max_tokens=MAX_TOKENS,
                system=system,
                tools=tools,
                messages=messages,
            )
        except Exception as e:
            log.error("API error: %s", e)
            break

        total_input_tokens += response.usage.input_tokens
        total_output_tokens += response.usage.output_tokens

        assistant_content = response.content
        messages.append({"role": "assistant", "content": assistant_content})

        if response.stop_reason == "end_turn":
            break

        if response.stop_reason == "tool_use":
            tool_results = []
            for block in assistant_content:
                if block.type == "tool_use":
                    tool_call_count += 1
                    if verbose:
                        log.info(
                            "  Tool[%d]: %s(%s)",
                            tool_call_count, block.name,
                            json.dumps(block.input)[:200],
                        )
                    result = dispatch_tool(block.name, block.input, sg=sg)
                    if verbose:
                        log.info("  -> %s", result[:200])
                    tool_results.append({
                        "type": "tool_result",
                        "tool_use_id": block.id,
                        "content": result,
                    })
            messages.append({"role": "user", "content": tool_results})
        else:
            break

    oracle_result = _extract_json_from_messages(messages)

    elapsed = time.time() - start_time
    costs = MODEL_COSTS.get(model, MODEL_COSTS[DEFAULT_MODEL])
    cost = (
        total_input_tokens * costs["input"] / 1_000_000
        + total_output_tokens * costs["output"] / 1_000_000
    )

    metadata = {
        "generator": "context_retrieval_agent",
        "model": model,
        "backend": backend,
        "input_tokens": total_input_tokens,
        "output_tokens": total_output_tokens,
        "tool_calls": tool_call_count,
        "elapsed_sec": round(elapsed, 1),
        "cost_usd": round(cost, 4),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }

    return oracle_result, metadata


# ---------------------------------------------------------------------------
# Cross-validation
# ---------------------------------------------------------------------------


def cross_validate_task(
    ctx: Dict[str, Any],
    repo_paths: Dict[str, Path],
    client: "anthropic.Anthropic",
    sg: Optional["SourcegraphClient"] = None,
    model: str = DEFAULT_MODEL,
    verbose: bool = False,
) -> Dict[str, Any]:
    """Run all backends on a single task and compare agreement.

    Returns a dict with per-backend results and agreement metrics.
    """
    results = {}
    backends_to_run = ["local", "hybrid"]
    if sg and sg.token:
        backends_to_run.append("deepsearch")

    for backend in backends_to_run:
        log.info("  Running backend: %s", backend)
        oracle, meta = run_agent(
            ctx, repo_paths, client,
            model=model, backend=backend, sg=sg, verbose=verbose,
        )
        results[backend] = {"oracle": oracle, "metadata": meta}

    # Compute pairwise file-level agreement
    agreement = {}
    backend_names = list(results.keys())
    for i, b1 in enumerate(backend_names):
        for b2 in backend_names[i + 1:]:
            files1 = {
                (f.get("repo", ""), f.get("path", ""))
                for f in results[b1]["oracle"].get("files", [])
            }
            files2 = {
                (f.get("repo", ""), f.get("path", ""))
                for f in results[b2]["oracle"].get("files", [])
            }
            intersection = files1 & files2
            union = files1 | files2
            jaccard = len(intersection) / len(union) if union else 1.0
            # F1-style agreement
            recall = len(intersection) / len(files1) if files1 else 1.0
            precision = len(intersection) / len(files2) if files2 else 1.0
            f1 = (2 * recall * precision / (recall + precision)) if (recall + precision) > 0 else 0.0
            agreement[f"{b1}_vs_{b2}"] = {
                "jaccard": round(jaccard, 4),
                "f1": round(f1, 4),
                "files_only_in_first": len(files1 - files2),
                "files_only_in_second": len(files2 - files1),
                "common_files": len(intersection),
            }

    # Also compare against existing oracle if available
    existing = ctx.get("existing_oracle", {})
    if existing and existing.get("files"):
        existing_files = {
            (f.get("repo", ""), f.get("path", ""))
            for f in existing.get("files", [])
        }
        for bname, bdata in results.items():
            agent_files = {
                (f.get("repo", ""), f.get("path", ""))
                for f in bdata["oracle"].get("files", [])
            }
            inter = existing_files & agent_files
            recall = len(inter) / len(existing_files) if existing_files else 1.0
            precision = len(inter) / len(agent_files) if agent_files else 1.0
            f1 = (2 * recall * precision / (recall + precision)) if (recall + precision) > 0 else 0.0
            agreement[f"{bname}_vs_existing_sg"] = {
                "f1": round(f1, 4),
                "recall_of_sg": round(recall, 4),
                "precision_vs_sg": round(precision, 4),
                "files_only_agent": len(agent_files - existing_files),
                "files_only_sg": len(existing_files - agent_files),
                "common": len(inter),
            }

    return {
        "task": f"{ctx.get('suite_name', '')}/{ctx.get('task_name', '')}",
        "results": {k: v["metadata"] for k, v in results.items()},
        "agreement": agreement,
        "oracles": {k: v["oracle"] for k, v in results.items()},
    }


def _extract_json_from_text(text: str) -> Optional[Dict[str, Any]]:
    """Try to extract oracle JSON from a text string.

    Tries in order:
      1. Fenced ```json block
      2. Balanced-brace search for outermost object containing "files"
      3. Raw parse of entire text
    Returns None if no valid JSON found.
    """
    if not text:
        return None

    # 1. Try to extract JSON from fenced block
    m = re.search(r"```json\s*\n(.*?)\n```", text, re.DOTALL)
    if m:
        try:
            return json.loads(m.group(1))
        except json.JSONDecodeError:
            pass

    # 2. Balanced-brace search — finds nested arrays/objects correctly
    depth = 0
    start = None
    for i, ch in enumerate(text):
        if ch == '{':
            if depth == 0:
                start = i
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0 and start is not None:
                candidate = text[start:i + 1]
                if '"files"' in candidate:
                    try:
                        parsed = json.loads(candidate)
                        if isinstance(parsed, dict):
                            return parsed
                    except json.JSONDecodeError:
                        pass
                start = None

    # 3. Try the whole text
    try:
        return json.loads(text)
    except (json.JSONDecodeError, ValueError):
        pass

    return None


def _extract_json_from_messages(messages: List[Dict]) -> Dict[str, Any]:
    """Extract the oracle JSON from the last assistant message."""
    for msg in reversed(messages):
        if msg.get("role") != "assistant":
            continue
        content = msg.get("content", "")
        if isinstance(content, list):
            text_parts = []
            for block in content:
                if hasattr(block, "text"):
                    text_parts.append(block.text)
                elif isinstance(block, dict) and block.get("type") == "text":
                    text_parts.append(block.get("text", ""))
            text = "\n".join(text_parts)
        else:
            text = str(content)

        result = _extract_json_from_text(text)
        if result is not None:
            return result

    return {"files": [], "text": "Agent did not produce valid JSON output."}


# ---------------------------------------------------------------------------
# Dual-Retrieval Verification
# ---------------------------------------------------------------------------


def verify_dual_retrieval(
    oracle: Dict[str, Any],
    repo_paths: Dict[str, Path],
    sg_client: Optional["SourcegraphClient"] = None,
) -> Dict[str, Any]:
    """Verify each oracle file is discoverable via local FS and Sourcegraph.

    Returns dict with per-file verification results and summary stats.
    Files that fail either check are flagged but NOT removed from the oracle.
    """
    files = oracle.get("files", [])
    verification = []

    for entry in files:
        repo = entry.get("repo", "")
        path = entry.get("path", "")

        # --- Local verification: file exists on disk in any repo_paths ---
        local_ok = False
        if repo_paths:
            # Try exact repo match first, then fall back to any repo dir
            for rname, rdir in repo_paths.items():
                candidate = rdir / path
                if candidate.is_file():
                    local_ok = True
                    break

        # --- Sourcegraph verification: keyword search returns results ---
        sg_ok = False
        if sg_client and sg_client.token:
            try:
                # Construct a precise file search query
                sg_query = f"file:^{re.escape(path)}$ count:1"
                if repo:
                    sg_query = f"repo:{repo} {sg_query}"
                result = sg_client.keyword_search(sg_query, max_results=1)
                sg_ok = result and "No results found" not in result and "error" not in result.lower()
            except Exception as e:
                log.debug("SG verify failed for %s:%s: %s", repo, path, e)

        verification.append({
            "repo": repo,
            "path": path,
            "local_verified": local_ok,
            "sg_verified": sg_ok,
        })

    # Summary stats
    n_total = len(verification)
    n_dual = sum(1 for v in verification if v["local_verified"] and v["sg_verified"])
    n_local_only = sum(1 for v in verification if v["local_verified"] and not v["sg_verified"])
    n_sg_only = sum(1 for v in verification if not v["local_verified"] and v["sg_verified"])
    n_unverified = sum(1 for v in verification if not v["local_verified"] and not v["sg_verified"])

    summary = {
        "n_total": n_total,
        "n_dual_verified": n_dual,
        "n_local_only": n_local_only,
        "n_sg_only": n_sg_only,
        "n_unverified": n_unverified,
    }

    log.info(
        "  Verification: %d/%d dual, %d local-only, %d sg-only, %d unverified",
        n_dual, n_total, n_local_only, n_sg_only, n_unverified,
    )

    return {"files": verification, "summary": summary}


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------


def write_curator_outputs(
    task_dir: Path,
    raw_oracle: Dict[str, Any],
    metadata: Dict[str, Any],
    ctx: Dict[str, Any],
    output_path: str = "",
    overwrite: bool = False,
) -> Dict[str, Path]:
    """Write all curator output files (ground_truth + oracle_answer + meta).

    Produces up to 3 files:
      1. ground_truth.json (or ground_truth_agent.json) — IR pipeline format
      2. oracle_answer.json (MCP-unique only) — artifact verifier format
      3. ground_truth_meta.json — sidecar with confidence and provenance

    If overwrite=False (default), existing files are not touched and the
    agent output is written to *_agent.json variants instead.

    Returns dict of output type -> file path.
    """
    tests_dir = task_dir / "tests"
    tests_dir.mkdir(exist_ok=True)
    outputs: Dict[str, Path] = {}

    # 1. ground_truth.json (ALL tasks, IR pipeline format)
    ir_gt = _convert_to_ir_schema(raw_oracle, ctx)
    if output_path:
        gt_path = Path(output_path)
    else:
        existing_gt = tests_dir / "ground_truth.json"
        if existing_gt.exists() and not overwrite:
            gt_path = tests_dir / "ground_truth_agent.json"
        else:
            gt_path = tests_dir / "ground_truth.json"
    gt_path.write_text(json.dumps(ir_gt, indent=2) + "\n")
    outputs["ground_truth"] = gt_path
    log.info("Wrote ground_truth: %s", gt_path)

    # 2. oracle_answer.json (MCP-unique only, artifact verifier format)
    suite = ctx.get("suite_name", "")
    if suite.startswith("ccb_mcp_"):
        oracle_fmt = _convert_to_oracle_schema(raw_oracle, ctx)
        oracle_fmt["_metadata"] = metadata
        existing_oracle = tests_dir / "oracle_answer.json"
        if existing_oracle.exists() and not overwrite:
            oracle_path = tests_dir / "oracle_answer_agent.json"
        else:
            oracle_path = tests_dir / "oracle_answer.json"
        oracle_path.write_text(json.dumps(oracle_fmt, indent=2) + "\n")
        outputs["oracle_answer"] = oracle_path
        log.info("Wrote oracle_answer: %s", oracle_path)

    # 3. ground_truth_meta.json (sidecar, ALL tasks)
    has_chunks = bool(ir_gt.get("chunks"))
    n_files = len(ir_gt.get("files", []))
    n_edit = len(ir_gt.get("expected_edit_files", []))
    has_test_sh = bool(ctx.get("test_sh_diff_targets"))

    if has_chunks and n_files >= 2:
        confidence = "high"
    elif n_files >= 1:
        confidence = "medium"
    else:
        confidence = "low"

    meta_sidecar = {
        "has_ground_truth": n_files > 0,
        "has_chunk_ground_truth": has_chunks,
        "ground_truth_source": "curator_agent",
        "ground_truth_confidence": confidence,
        "task_name": ctx.get("task_name", ""),
        "curator_agent_version": "2.0",
        "model": metadata.get("model", ""),
        "backend": metadata.get("backend", ""),
        "timestamp": metadata.get("timestamp", ""),
        "files_count": n_files,
        "edit_files_count": n_edit,
        "chunks_count": len(ir_gt.get("chunks", [])),
        "symbols_count": len(ir_gt.get("symbols", [])),
        "cost_usd": metadata.get("cost_usd", 0),
        "elapsed_sec": metadata.get("elapsed_sec", 0),
        "exploration_notes": raw_oracle.get("text", "")[:500],
    }
    meta_path = tests_dir / "ground_truth_meta.json"
    meta_path.write_text(json.dumps(meta_sidecar, indent=2) + "\n")
    outputs["meta"] = meta_path
    log.info("Wrote metadata: %s", meta_path)

    return outputs


# Keep backward-compatible alias for any callers
def write_oracle(
    task_dir: Path,
    oracle: Dict[str, Any],
    metadata: Dict[str, Any],
    output_path: str = "",
) -> Path:
    """Backward-compatible wrapper. Prefer write_curator_outputs()."""
    oracle["_metadata"] = metadata
    if output_path:
        out = Path(output_path)
    else:
        tests_dir = task_dir / "tests"
        tests_dir.mkdir(exist_ok=True)
        suite = task_dir.parent.name
        if suite.startswith("ccb_mcp_"):
            out = tests_dir / "oracle_answer_agent.json"
        else:
            out = tests_dir / "ground_truth_agent.json"
    out.write_text(json.dumps(oracle, indent=2) + "\n")
    log.info("Wrote: %s", out)
    return out


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Context retrieval agent with multiple backends for oracle cross-validation"
    )
    # Task selection
    parser.add_argument(
        "--task-dir", type=str, default="",
        help="Single task directory to process",
    )
    parser.add_argument(
        "--suite", type=str, default="",
        help="Process all tasks in a suite (e.g., ccb_mcp_crossrepo_tracing)",
    )
    parser.add_argument(
        "--sdlc-all", action="store_true",
        help="Process all SDLC tasks",
    )
    parser.add_argument(
        "--mcp-all", action="store_true",
        help="Process all MCP-unique tasks",
    )
    # Agent configuration
    parser.add_argument(
        "--model", type=str, default=DEFAULT_MODEL,
        help=f"Model to use (default: {DEFAULT_MODEL})",
    )
    parser.add_argument(
        "--backend", type=str, default="hybrid", choices=BACKENDS,
        help="Tool backend: local, deepsearch, or hybrid (default: hybrid)",
    )
    parser.add_argument(
        "--cross-validate", action="store_true",
        help="Run ALL backends on each task and report agreement metrics",
    )
    # Output
    parser.add_argument(
        "--output", type=str, default="",
        help="Override output file path (single-task mode only)",
    )
    parser.add_argument(
        "--output-dir", type=str, default="",
        help="Output directory for batch mode",
    )
    # Limits
    parser.add_argument(
        "--max-cost", type=float, default=0,
        help="Stop after spending this many USD (0 = unlimited)",
    )
    parser.add_argument(
        "--max-tasks", type=int, default=0,
        help="Process at most N tasks (0 = all). Useful for pilot runs.",
    )
    parser.add_argument(
        "--skip-existing", action="store_true",
        help="Skip tasks that already have an agent-generated oracle",
    )
    parser.add_argument(
        "--missing-only", action="store_true",
        help="Only process tasks that have NO ground truth at all (no oracle_answer.json, no ground_truth.json)",
    )
    parser.add_argument(
        "--no-verify", action="store_true",
        help="Skip dual-retrieval verification pass",
    )
    parser.add_argument(
        "--overwrite-existing", action="store_true",
        help="Overwrite existing ground_truth.json / oracle_answer.json (default: write to _agent variants)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show tasks without running agent",
    )
    parser.add_argument(
        "--verbose", action="store_true",
        help="Verbose logging",
    )
    # Execution mode
    cli_group = parser.add_mutually_exclusive_group()
    cli_group.add_argument(
        "--use-cli", action="store_true", default=True,
        help="Use Claude CLI for subscription billing (default)",
    )
    cli_group.add_argument(
        "--use-sdk", action="store_true",
        help="Use Anthropic SDK directly (requires ANTHROPIC_API_KEY)",
    )
    args = parser.parse_args()
    use_cli = not args.use_sdk

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )

    if use_cli:
        log.info("Using Claude CLI (subscription billing)")
    else:
        if not HAS_ANTHROPIC:
            log.error("anthropic package not installed. pip install anthropic")
            return 1

        # OAuth token preferred (subscription billing), API key fallback
        api_key = os.environ.get("CLAUDE_CODE_OAUTH_TOKEN", "")
        if api_key:
            log.info("Using OAuth token (CLAUDE_CODE_OAUTH_TOKEN)")
        else:
            api_key = os.environ.get("ANTHROPIC_API_KEY", "")
            if api_key:
                log.info("Using API key (ANTHROPIC_API_KEY)")
        if not api_key and not args.dry_run:
            log.error("Set CLAUDE_CODE_OAUTH_TOKEN or ANTHROPIC_API_KEY")
            return 1

    # Discover tasks
    tasks = discover_tasks(
        suite=args.suite,
        task_dir=args.task_dir,
        sdlc_all=args.sdlc_all,
        mcp_all=args.mcp_all,
    )
    if not tasks:
        log.error("No tasks found")
        return 1

    # Filter tasks based on flags
    original_count = len(tasks)
    if args.skip_existing or args.missing_only:
        filtered = []
        for t in tasks:
            tests_dir = t / "tests"
            suite = t.parent.name
            # Check for agent-generated oracle
            if args.skip_existing:
                if suite.startswith("ccb_mcp_"):
                    if (tests_dir / "oracle_answer_agent.json").exists():
                        continue
                else:
                    if (tests_dir / "ground_truth_agent.json").exists():
                        continue
            # Check for ANY ground truth
            if args.missing_only:
                has_any = (
                    (tests_dir / "oracle_answer.json").exists()
                    or (tests_dir / "ground_truth.json").exists()
                )
                if has_any:
                    continue
            filtered.append(t)
        tasks = filtered
        log.info("Filtered %d -> %d tasks (skip_existing=%s, missing_only=%s)",
                 original_count, len(tasks), args.skip_existing, args.missing_only)

    if args.max_tasks > 0:
        tasks = tasks[:args.max_tasks]

    log.info("Found %d tasks (model=%s, backend=%s)", len(tasks), args.model, args.backend)

    if args.dry_run:
        for t in tasks:
            ctx = load_task_context(t)
            has_oracle = "existing_oracle" in ctx or "existing_ground_truth" in ctx
            print(f"  {'[HAS_GT]' if has_oracle else '[MISSING]'} {t.parent.name}/{t.name}")
        print(f"\nTotal: {len(tasks)} tasks")
        costs = MODEL_COSTS.get(args.model, MODEL_COSTS[DEFAULT_MODEL])
        est_cost = len(tasks) * 0.50  # rough estimate
        print(f"Estimated cost: ~${est_cost:.0f} ({args.model})")
        return 0

    client = None
    sg = None
    if not use_cli:
        client = anthropic.Anthropic(api_key=api_key)
        # Set up Sourcegraph client if needed (SDK mode only)
        if args.backend in ("deepsearch", "hybrid") or args.cross_validate:
            sg = SourcegraphClient()
            if not sg.token:
                if args.backend == "deepsearch":
                    log.error("SOURCEGRAPH_ACCESS_TOKEN required for deepsearch backend")
                    return 1
                log.warning("No SG token — deepsearch tools will be unavailable")
    cache_dir = get_cache_dir()

    total_cost = 0.0
    results_summary = []
    cross_val_results = []

    for i, task_dir in enumerate(tasks):
        if args.max_cost > 0 and total_cost >= args.max_cost:
            log.warning(
                "Cost limit reached ($%.2f >= $%.2f). Stopping.",
                total_cost, args.max_cost,
            )
            break

        log.info(
            "[%d/%d] Processing %s/%s",
            i + 1, len(tasks), task_dir.parent.name, task_dir.name,
        )

        ctx = parse_task_for_curator(task_dir)

        # Get repo paths (needed for local/hybrid backends)
        repo_paths = {}
        if args.backend != "deepsearch" or args.cross_validate:
            repo_paths = _resolve_repos(ctx, cache_dir)
            if not repo_paths and args.backend == "local":
                log.warning("  No repos available, skipping")
                continue

        if args.cross_validate:
            # Run all backends and compare
            try:
                cv_result = cross_validate_task(
                    ctx, repo_paths, client, sg=sg,
                    model=args.model, verbose=args.verbose,
                )
                cross_val_results.append(cv_result)
                # Sum costs across backends
                task_cost = sum(
                    m.get("cost_usd", 0) for m in cv_result["results"].values()
                )
                total_cost += task_cost
                log.info("  Agreement: %s", json.dumps(cv_result["agreement"], indent=2))
            except Exception as e:
                log.error("  Cross-validation failed: %s", e)
            continue

        # Single-backend run
        try:
            if use_cli:
                oracle, metadata = run_agent_cli(
                    ctx, repo_paths,
                    model=args.model, backend=args.backend,
                    verbose=args.verbose,
                )
            else:
                oracle, metadata = run_agent(
                    ctx, repo_paths, client,
                    model=args.model, backend=args.backend,
                    sg=sg, verbose=args.verbose,
                )
        except Exception as e:
            log.error("  Agent failed: %s", e)
            continue

        total_cost += metadata.get("cost_usd", 0)

        # Write output — use curator outputs (ground_truth + oracle + meta)
        output_path = ""
        if args.output and len(tasks) == 1:
            output_path = args.output
        elif args.output_dir:
            out_dir = Path(args.output_dir) / task_dir.parent.name
            out_dir.mkdir(parents=True, exist_ok=True)
            suite = task_dir.parent.name
            if suite.startswith("ccb_mcp_"):
                output_path = str(out_dir / f"{task_dir.name}_oracle_agent.json")
            else:
                output_path = str(out_dir / f"{task_dir.name}_gt_agent.json")

        # Dual-retrieval verification (unless --no-verify)
        if not args.no_verify:
            vr = verify_dual_retrieval(oracle, repo_paths, sg_client=sg)
            metadata["dual_verification"] = vr["summary"]

        outputs = write_curator_outputs(
            task_dir, oracle, metadata, ctx,
            output_path=output_path,
            overwrite=args.overwrite_existing,
        )

        n_files = len(oracle.get("files", []))
        n_symbols = len(oracle.get("symbols", []))
        n_chunks = len(oracle.get("chunks", []))
        results_summary.append({
            "task": f"{task_dir.parent.name}/{task_dir.name}",
            "files_found": n_files,
            "symbols_found": n_symbols,
            "chunks_found": n_chunks,
            "cost_usd": metadata["cost_usd"],
            "tool_calls": metadata["tool_calls"],
            "elapsed_sec": metadata["elapsed_sec"],
            "outputs": {k: str(v) for k, v in outputs.items()},
        })

        log.info(
            "  -> %d files, %d symbols, %d chunks, $%.4f, %d tool calls, %.1fs",
            n_files, n_symbols, n_chunks, metadata["cost_usd"],
            metadata["tool_calls"], metadata["elapsed_sec"],
        )

    # Summary
    print(f"\n{'=' * 60}")
    if args.cross_validate and cross_val_results:
        print(f"Cross-validated: {len(cross_val_results)} tasks")
        print(f"Total cost: ${total_cost:.4f}")
        # Aggregate agreement
        for pair_key in cross_val_results[0].get("agreement", {}):
            f1s = [
                r["agreement"][pair_key]["f1"]
                for r in cross_val_results
                if pair_key in r.get("agreement", {})
            ]
            if f1s:
                avg_f1 = sum(f1s) / len(f1s)
                print(f"  {pair_key}: avg F1 = {avg_f1:.4f} (n={len(f1s)})")
        # Write detailed results
        cv_report_path = Path(args.output_dir or ".") / "cross_validation_report.json"
        cv_report_path.write_text(json.dumps(cross_val_results, indent=2) + "\n")
        print(f"\nDetailed report: {cv_report_path}")
    else:
        print(f"Processed: {len(results_summary)}/{len(tasks)} tasks")
        print(f"Total cost: ${total_cost:.4f}")
        if results_summary:
            avg_files = sum(r["files_found"] for r in results_summary) / len(results_summary)
            avg_cost = total_cost / len(results_summary)
            print(f"Avg files/task: {avg_files:.1f}")
            print(f"Avg cost/task: ${avg_cost:.4f}")
    print(f"{'=' * 60}")

    return 0


def _resolve_repos(
    ctx: Dict[str, Any], cache_dir: Path
) -> Dict[str, Path]:
    """Resolve repos for a task — clone if needed, return path mapping."""
    repo_paths: Dict[str, Path] = {}

    # Strategy 1: Use repo fixture (MCP-unique tasks)
    fixture = ctx.get("repo_fixture")
    if fixture:
        specs = fixture.get("repos", [])
        return ensure_repos_cloned(specs, cache_dir)

    # Strategy 2: Extract from Dockerfile clone URLs
    clone_urls = ctx.get("repo_urls", [])
    for entry in clone_urls:
        slug = entry.get("slug", "")
        target = entry.get("target", "")
        if slug:
            try:
                path = clone_repo(slug, cache_dir)
                # Use both slug and target as keys
                repo_paths[slug] = path
                if target and target != ".":
                    repo_paths[target] = path
            except Exception as e:
                log.warning("Failed to clone %s: %s", slug, e)

    return repo_paths


if __name__ == "__main__":
    sys.exit(main())
